[package]
name = "RuinOS"
version = "0.1.0"
authors = ["mocomaminecraft <mocomaminecraft@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
